### ISSUE TITLE
Misses the ENTRYPOINT

### ISSUE THREAD

**Issue by peter279k** [kadnan/DockerPHPTutorial#1]
As title, it seems that the `ENTRYPOINT ` should be added in `Dockerfile`.

I suggest that the `ENTRYPOINT` is the `bash` and it can help developers to use `docker run` easily/conveniently.

**Comment by kadnan** [comment]
Make a pull request

**Comment by peter279k** [comment]
The `ENTRYPOINT` is not necessary if we use the `docker-compose` to build the docker containers.

I found other issues, and create related PR about this.
