### ISSUE TITLE
Integrate Travis CI service

### ISSUE THREAD

**Issue by peter279k** [kadnan/DockerPHPTutorial#3]
As title, could you add the [Travis CI service](https://travis-ci.org/)?

And add the Travis CI badge.

**Comment by kadnan** [comment]
@peter279k I am kind of ignorant about it, could you generate a relevant link as provided [here](https://stackoverflow.com/questions/19810386/showing-travis-build-status-in-github-repo)?

**Comment by peter279k** [comment]
@kadnan, thank you for your reply.

Before adding badge, I think you should add the Travis CI service hook via Travis CI site.

You can visit this [site](https://travis-ci.org/account/repositories) to know what I mean :).

**Comment by kadnan** [comment]
@peter279k 
I am busy atm. I have set it up and here is the badge code

[![Build Status](https://travis-ci.org/kadnan/DockerPHPTutorial.svg?branch=master)](https://travis-ci.org/kadnan/DockerPHPTutorial)


Could you update the README?

**Comment by peter279k** [comment]
@kadnan, thank you for your reply.

I can update the Travis CI badge link :).

**Comment by peter279k** [comment]
Closes issue via PR #4.
